// Created by iWeb 3.0.2 local-build-20200225

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,530),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_9.png'},{rect:new IWRect(1,-1,608,2),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_10.png'},{rect:new IWRect(609,-1,3,2),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_11.png'},{rect:new IWRect(609,1,3,530),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_12.png'},{rect:new IWRect(609,531,3,3),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_13.png'},{rect:new IWRect(1,531,608,3),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_14.png'},{rect:new IWRect(-1,531,2,3),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_15.png'}],new IWSize(610,532)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,629),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_1.png'},{rect:new IWRect(1,-1,608,2),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_2.png'},{rect:new IWRect(609,-1,3,2),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_3.png'},{rect:new IWRect(609,1,3,629),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_4.png'},{rect:new IWRect(609,630,3,3),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_5.png'},{rect:new IWRect(1,630,608,3),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_6.png'},{rect:new IWRect(-1,630,2,3),url:'23_The_World_Wide_Web_turns_25_years_old_today_files/stroke_7.png'}],new IWSize(610,631))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('23_The_World_Wide_Web_turns_25_years_old_today_files/23_The_World_Wide_Web_turns_25_years_old_todayMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');Widget.onload();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
