// Created by iWeb 3.0.4 local-build-20200628

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.500000}),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,235),url:'12_The_Dark_Side_of_GNU_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'12_The_Dark_Side_of_GNU_files/stroke_1.png'},{rect:new IWRect(1,-1,608,2),url:'12_The_Dark_Side_of_GNU_files/stroke_2.png'},{rect:new IWRect(609,-1,2,2),url:'12_The_Dark_Side_of_GNU_files/stroke_3.png'},{rect:new IWRect(609,1,2,235),url:'12_The_Dark_Side_of_GNU_files/stroke_4.png'},{rect:new IWRect(609,236,2,3),url:'12_The_Dark_Side_of_GNU_files/stroke_5.png'},{rect:new IWRect(1,236,608,3),url:'12_The_Dark_Side_of_GNU_files/stroke_6.png'},{rect:new IWRect(-1,236,2,3),url:'12_The_Dark_Side_of_GNU_files/stroke_7.png'}],new IWSize(610,237)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,515),url:'12_The_Dark_Side_of_GNU_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'12_The_Dark_Side_of_GNU_files/stroke_9.png'},{rect:new IWRect(1,-1,498,2),url:'12_The_Dark_Side_of_GNU_files/stroke_10.png'},{rect:new IWRect(499,-1,2,2),url:'12_The_Dark_Side_of_GNU_files/stroke_11.png'},{rect:new IWRect(499,1,2,515),url:'12_The_Dark_Side_of_GNU_files/stroke_12.png'},{rect:new IWRect(499,516,2,2),url:'12_The_Dark_Side_of_GNU_files/stroke_13.png'},{rect:new IWRect(1,516,498,2),url:'12_The_Dark_Side_of_GNU_files/stroke_14.png'},{rect:new IWRect(-1,516,2,2),url:'12_The_Dark_Side_of_GNU_files/stroke_15.png'}],new IWSize(500,517))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('12_The_Dark_Side_of_GNU_files/12_The_Dark_Side_of_GNUMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');Widget.onload();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
