// Created by iWeb 3.0.4 local-build-20200628

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,90),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_9.png'},{rect:new IWRect(2,-2,494,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_10.png'},{rect:new IWRect(496,-2,4,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_11.png'},{rect:new IWRect(496,2,4,90),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_12.png'},{rect:new IWRect(496,92,4,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_13.png'},{rect:new IWRect(2,92,494,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_14.png'},{rect:new IWRect(-2,92,4,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_15.png'}],new IWSize(498,94)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,404),url:'16_Online_teaching_advice_from_a_veteran_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_1.png'},{rect:new IWRect(1,-1,345,2),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_2.png'},{rect:new IWRect(346,-1,2,2),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_3.png'},{rect:new IWRect(346,1,2,404),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_4.png'},{rect:new IWRect(346,405,2,3),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_5.png'},{rect:new IWRect(1,405,345,3),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_6.png'},{rect:new IWRect(-1,405,2,3),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_7.png'}],new IWSize(347,406)),stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,215),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_17.png'},{rect:new IWRect(2,-2,548,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_18.png'},{rect:new IWRect(550,-2,4,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_19.png'},{rect:new IWRect(550,2,4,215),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_20.png'},{rect:new IWRect(550,217,4,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_21.png'},{rect:new IWRect(2,217,548,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_22.png'},{rect:new IWRect(-2,217,4,4),url:'16_Online_teaching_advice_from_a_veteran_files/stroke_23.png'}],new IWSize(552,219))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('16_Online_teaching_advice_from_a_veteran_files/16_Online_teaching_advice_from_a_veteranMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');Widget.onload();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
