// Created by iWeb 3.0.2 local-build-20200627

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,318),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_1.png'},{rect:new IWRect(1,-1,608,2),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_2.png'},{rect:new IWRect(609,-1,3,2),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_3.png'},{rect:new IWRect(609,1,3,318),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_4.png'},{rect:new IWRect(609,319,3,3),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_5.png'},{rect:new IWRect(1,319,608,3),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_6.png'},{rect:new IWRect(-1,319,2,3),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_7.png'}],new IWSize(610,320)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,303),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_9.png'},{rect:new IWRect(1,-1,608,2),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_10.png'},{rect:new IWRect(609,-1,3,2),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_11.png'},{rect:new IWRect(609,1,3,303),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_12.png'},{rect:new IWRect(609,304,3,3),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_13.png'},{rect:new IWRect(1,304,608,3),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_14.png'},{rect:new IWRect(-1,304,2,3),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_15.png'}],new IWSize(610,305)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,125),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_17.png'},{rect:new IWRect(1,-1,298,2),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_18.png'},{rect:new IWRect(299,-1,2,2),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_19.png'},{rect:new IWRect(299,1,2,125),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_20.png'},{rect:new IWRect(299,126,2,3),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_21.png'},{rect:new IWRect(1,126,298,3),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_22.png'},{rect:new IWRect(-1,126,2,3),url:'19_Three_reasons_why_incubators_breed_failure_files/stroke_23.png'}],new IWSize(300,127))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('19_Three_reasons_why_incubators_breed_failure_files/19_Three_reasons_why_incubators_breed_failureMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');Widget.onload();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
